properties:
  - type: secure
    name: apikey
    value: ${API_KEY}
  - type: text
    name: ibmcloud-api
    value: ${IBM_CLOUD_API}
  - type: text
    name: enable-automatic-plan-apply
    value: ${ENABLE_PLAN_APPLY}
  - name: pipeline-debug
    type: single_select
    value:
      "0": true
      "1": false
triggers:
  - type: git
    pattern: ${APP_BRANCH}
    events:
      pull_request: true
    name: Git Trigger - PR
    eventListener: ${event-listener-name}
    properties:
      - type: secure
        name: TF_VAR_ibmcloud_api_key
        value: ${API_KEY}
      - type: text
        name: tf-dir
        value: ./
    service: ${terraform-template}
inputs:
  - type: git
    path: .tekton
    branch: ${TEMPLATE_BRANCH}
    service: ${schematics-pipeline}
  - type: git
    path: cra
    branch: ${CATALOG_BRANCH}
    service: ${tekton-catalog}
  - type: git
    path: git
    branch: ${CATALOG_BRANCH}
    service: ${tekton-catalog}
  - type: git
    path: toolchain
    branch: ${CATALOG_BRANCH}
    service: ${tekton-catalog}
