---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pr-pipeline
spec:
  params:
    - name: repository
      description: the git repo
    - name: branch
      description: branch
    - name: revision
      description: the git revision/commit for the git repo
      default: ""
    - name: target-branch
      description: target branch
    - name: commit-id
      description: commit id
    - name: commit-timestamp
      description: commit timestamp
    - name: pr-url
      description: pr url
    - name: target-commit-id
      description: target branch commit id
    - name: project-id
      description: project id
      default: ""
    - name: scm-type
      description: source code type used (github, github-ent, gitlab)
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: WORKSPACE_ID
      description: workspace id
    - name: ibmcloud-region
      description: (Optional) ibmcloud region to use
      default: ""
    - name: pipeline-debug
      description: Toggles debug mode for the pipeline
      default: "0"
    - name: resource-group
      description: (Optional) Target resource group (name or id) for the ibmcloud login operation
      default: ""

    # Common command related params
    - name: custom-script
      description: (Optional) A custom script to be ran prior to CRA scanning
    - name: ibmcloud-trace
      description: (Optional) Enables IBMCLOUD_TRACE for ibmcloud cli logging
    - name: verbose
      description: (Optional) Enables IBMCLOUD_TRACE for ibmcloud cli logging
    - name: output
      description: (Optional) Prints command result to console
    - name: path
      description: Repository path to scan
    - name: strict
      description: (Optional) Enables strict mode for scanning
    - name: toolchainid
      description: (Optional) The target toolchain id to be used. Defaults to the current toolchain id
    - name: verbose
      description: (Optional) Enable verbose log messages

      # CRA Terraform related parameters
    - name: terraform-report
      description: Filepath to store generated Terraform report. Default to `./terraform.json`
    - name: tf-dir
      description: The directory where the terraform main entry file is found if not in parent directory
    - name: tf-plan
      description: (Optional) Filepath to Terraform Plan file.
    - name: tf-var-file
      description: (Optional) terraform var-file
    - name: tf-version
      description: (Optional) The terraform version to use to create Terraform plan
    - name: tf-policy-file
      description: (Optional) Filepath to policy profile. This file should contain "scc_goals" and "scc_goal_parameters" that will overwrite default checks.
    - name: tf-format
      description: (Optional) Report format. Requires --policy-file. Supported values [OSCAL]
    - name: tf-state-file
      description: (Optional) Path of terraform state file. Requires --format to be set to OSCAL.

  workspaces:
    - name: artifacts
  tasks:
    - name: extract-repository-url
      taskRef:
        name: toolchain-extract-value
      params:
        - name: expression
          # if a params.repository is given, it takes precedence
          value: '. as $toolchain | ["$(params.repository)"] | if .[0]=="" then $toolchain | .services[] | select(.toolchain_binding.name=="repo") | .dashboard_url else .[0] end'
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    - name: cra-fetch-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: ibmcloud-apikey-secret-key
          value: "apikey"
        - name: repository
          value: $(tasks.extract-repository-url.results.extracted-value)
        - name: branch
          value: $(params.branch)
        - name: revision
          value: $(params.revision)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
      workspaces:
        - name: output
          workspace: artifacts
    - name: cra-terraform-scan
      runAfter:
        - cra-fetch-repo
      taskRef:
        name: cra-terraform-scan-v2
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: ibmcloud-region
          value: $(params.ibmcloud-region)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: resource-group
          value: $(params.resource-group)
        - name: custom-script
          value: $(params.custom-script)
        - name: ibmcloud-trace
          value: $(params.ibmcloud-trace)
        - name: output
          value: $(params.output)
        - name: path
          value: $(params.path)
        - name: strict
          value: $(params.strict)
        - name: toolchainid
          value: $(params.toolchainid)
        - name: verbose
          value: $(params.verbose)
        - name: terraform-report
          value: $(params.terraform-report)
        - name: tf-dir
          value: $(params.tf-dir)
        - name: tf-plan
          value: $(params.tf-plan)
        - name: tf-var-file
          value: $(params.tf-var-file)
        - name: tf-policy-file
          value: $(params.tf-policy-file)
        - name: tf-version
          value: $(params.tf-version)
        - name: tf-format
          value: $(params.tf-format)
        - name: tf-state-file
          value: $(params.tf-state-file)
