---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pr-template
spec:
  params:
    - name: repository
      description: The git repo
    - name: branch
      description: branch
    - name: target-branch
      description: target branch
    - name: target-commit-id
      description: target commit id
    - name: apikey
      description: the ibmcloud api key
    - name: ibmcloud-api
      description: The ibmcloud api
      default: "https://cloud.ibm.com"
    - name: ibmcloud-region
      description: (Optional) ibmcloud region to use
      default: ""
    - name: pipeline-debug
      description: Toggles debug mode for the pipeline
      default: "0"
    - name: registry-region
      description: (Optional) The ibmcloud container registry region
      default: ""
    - name: resource-group
      description: (Optional) Target resource group (name or id) for the ibmcloud login operation
      default: ""
    - name: commit-id
      description: commit id
    - name: commit-timestamp
      description: commit timestamp
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
      default: "0"
    - name: WORKSPACE_ID
      description: The workspace id
    - name: pr-url
      description: PR url
    - name: pr-number
      description: PR number
    - name: pr-name
      description: PR name
    - name: scm-type
      description: source code type used (github, github-ent, gitlab)
    - name: project-id
      description: project id
      default: ""

    # Terraform related parameters
    - name: terraform-report
      description: Filepath to store generated Terraform report
      default: "terraform.json"
    - name: tf-dir
      description: (Optional) The directory where the terraform main entry file is found if not in parent directory
      default: ""
    - name: tf-plan
      description: (Optional) Filepath to Terraform Plan file.
      default: ""
    - name: tf-var-file
      description: (Optional) terraform var-file
      default: ""
    - name: tf-version
      description: (Optional) The terraform version to use to create Terraform plan
      default: "0.15.5"
    - name: tf-policy-file
      description: (Optional) Filepath to policy profile. This file should contain "scc_goals" and "scc_goal_parameters" that will overwrite default checks
      default: ""
    - name: tf-format
      description: (Optional) Report format. Requires --policy-file. Supported values [OSCAL]
      default: ""
    - name: tf-state-file
      description: (Optional) Path of terraform state file. Requires --format to be set to OSCAL.
      default: ""
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pr-pipeline
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: target-branch
            value: $(params.target-branch)
          - name: commit-id
            value: $(params.commit-id)
          - name: commit-timestamp
            value: $(params.commit-timestamp)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: WORKSPACE_ID
            value: $(params.WORKSPACE_ID)
          - name: pr-url
            value: $(params.pr-url)
          - name: target-commit-id
            value: $(params.target-commit-id)
          - name: scm-type
            value: $(params.scm-type)
          - name: project-id
            value: $(params.project-id)
          - name: ibmcloud-api
            value: $(params.ibmcloud-api)
          - name: ibmcloud-region
            value: $(params.ibmcloud-region)
          - name: resource-group
            value: $(params.resource-group)
          - name: custom-script
            value: $(params.custom-script)
          - name: ibmcloud-trace
            value: $(params.ibmcloud-trace)
          - name: output
            value: $(params.output)
          - name: path
            value: $(params.path)
          - name: strict
            value: $(params.strict)
          - name: toolchainid
            value: $(params.toolchainid)
          - name: verbose
            value: $(params.verbose)
          - name: terraform-report
            value: $(params.terraform-report)
          - name: tf-dir
            value: $(params.tf-dir)
          - name: tf-plan
            value: $(params.tf-plan)
          - name: tf-var-file
            value: $(params.tf-var-file)
          - name: tf-policy-file
            value: $(params.tf-policy-file)
          - name: tf-version
            value: $(params.tf-version)
          - name: tf-format
            value: $(params.tf-format)
          - name: tf-state-file
            value: $(params.tf-state-file)
